plugins:
  - "prettier-plugin-solidity"
printWidth: 120
trailingComma: "all"
endOfLine: "lf"

overrides:
  - files: "*.md"
    options:
      proseWrap: "always"
  - files: "*.sol"
    options:
      compiler: "0.8.27"
      parser: "solidity-parse"
      tabWidth: 4
