/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace RockPaperArena {
  export type MatchStruct = {
    matchId: BigNumberish;
    player1: AddressLike;
    player2: AddressLike;
    move1: BytesLike;
    move2: BytesLike;
    player1Committed: boolean;
    player2Committed: boolean;
    createdAt: BigNumberish;
    state: BigNumberish;
    winner: AddressLike;
  };

  export type MatchStructOutput = [
    matchId: bigint,
    player1: string,
    player2: string,
    move1: string,
    move2: string,
    player1Committed: boolean,
    player2Committed: boolean,
    createdAt: bigint,
    state: bigint,
    winner: string
  ] & {
    matchId: bigint;
    player1: string;
    player2: string;
    move1: string;
    move2: string;
    player1Committed: boolean;
    player2Committed: boolean;
    createdAt: bigint;
    state: bigint;
    winner: string;
  };

  export type PlayerStatsStruct = {
    wins: BigNumberish;
    losses: BigNumberish;
    draws: BigNumberish;
    totalMatches: BigNumberish;
    currentStreak: BigNumberish;
  };

  export type PlayerStatsStructOutput = [
    wins: bigint,
    losses: bigint,
    draws: bigint,
    totalMatches: bigint,
    currentStreak: bigint
  ] & {
    wins: bigint;
    losses: bigint;
    draws: bigint;
    totalMatches: bigint;
    currentStreak: bigint;
  };
}

export interface RockPaperArenaInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "acceptChallenge"
      | "cancelMatch"
      | "claimRewards"
      | "confidentialProtocolId"
      | "createChallenge"
      | "getMatch"
      | "getPendingMatches"
      | "getPlayerStats"
      | "lockMove"
      | "matchCounter"
      | "matches"
      | "pendingMatches"
      | "playerActiveMatch"
      | "playerStats"
      | "requestReveal"
      | "submitMove"
      | "updateStreak"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "MatchCancelled"
      | "MatchCreated"
      | "MatchJoined"
      | "MatchRevealed"
      | "MoveCommitted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "acceptChallenge",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelMatch",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimRewards",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createChallenge",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMatch",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPendingMatches",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPlayerStats",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lockMove",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "matchCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "matches",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "pendingMatches",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "playerActiveMatch",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "playerStats",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "requestReveal",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submitMove",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateStreak",
    values: [AddressLike, boolean]
  ): string;

  decodeFunctionResult(
    functionFragment: "acceptChallenge",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelMatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createChallenge",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getMatch", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getPendingMatches",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPlayerStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "lockMove", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "matchCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "matches", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingMatches",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "playerActiveMatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "playerStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestReveal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "submitMove", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateStreak",
    data: BytesLike
  ): Result;
}

export namespace MatchCancelledEvent {
  export type InputTuple = [matchId: BigNumberish];
  export type OutputTuple = [matchId: bigint];
  export interface OutputObject {
    matchId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MatchCreatedEvent {
  export type InputTuple = [matchId: BigNumberish, player1: AddressLike];
  export type OutputTuple = [matchId: bigint, player1: string];
  export interface OutputObject {
    matchId: bigint;
    player1: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MatchJoinedEvent {
  export type InputTuple = [matchId: BigNumberish, player2: AddressLike];
  export type OutputTuple = [matchId: bigint, player2: string];
  export interface OutputObject {
    matchId: bigint;
    player2: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MatchRevealedEvent {
  export type InputTuple = [
    matchId: BigNumberish,
    winner: AddressLike,
    result: BigNumberish
  ];
  export type OutputTuple = [matchId: bigint, winner: string, result: bigint];
  export interface OutputObject {
    matchId: bigint;
    winner: string;
    result: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MoveCommittedEvent {
  export type InputTuple = [matchId: BigNumberish, player: AddressLike];
  export type OutputTuple = [matchId: bigint, player: string];
  export interface OutputObject {
    matchId: bigint;
    player: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface RockPaperArena extends BaseContract {
  connect(runner?: ContractRunner | null): RockPaperArena;
  waitForDeployment(): Promise<this>;

  interface: RockPaperArenaInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  acceptChallenge: TypedContractMethod<
    [matchId: BigNumberish],
    [void],
    "nonpayable"
  >;

  cancelMatch: TypedContractMethod<
    [matchId: BigNumberish],
    [void],
    "nonpayable"
  >;

  claimRewards: TypedContractMethod<[], [void], "view">;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  createChallenge: TypedContractMethod<[], [bigint], "nonpayable">;

  getMatch: TypedContractMethod<
    [matchId: BigNumberish],
    [RockPaperArena.MatchStructOutput],
    "view"
  >;

  getPendingMatches: TypedContractMethod<[], [bigint[]], "view">;

  getPlayerStats: TypedContractMethod<
    [player: AddressLike],
    [RockPaperArena.PlayerStatsStructOutput],
    "view"
  >;

  lockMove: TypedContractMethod<[matchId: BigNumberish], [boolean], "view">;

  matchCounter: TypedContractMethod<[], [bigint], "view">;

  matches: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        string,
        boolean,
        boolean,
        bigint,
        bigint,
        string
      ] & {
        matchId: bigint;
        player1: string;
        player2: string;
        move1: string;
        move2: string;
        player1Committed: boolean;
        player2Committed: boolean;
        createdAt: bigint;
        state: bigint;
        winner: string;
      }
    ],
    "view"
  >;

  pendingMatches: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  playerActiveMatch: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  playerStats: TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        wins: bigint;
        losses: bigint;
        draws: bigint;
        totalMatches: bigint;
        currentStreak: bigint;
      }
    ],
    "view"
  >;

  requestReveal: TypedContractMethod<
    [matchId: BigNumberish],
    [void],
    "nonpayable"
  >;

  submitMove: TypedContractMethod<
    [matchId: BigNumberish, encryptedMove: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  updateStreak: TypedContractMethod<
    [arg0: AddressLike, arg1: boolean],
    [void],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "acceptChallenge"
  ): TypedContractMethod<[matchId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "cancelMatch"
  ): TypedContractMethod<[matchId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimRewards"
  ): TypedContractMethod<[], [void], "view">;
  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "createChallenge"
  ): TypedContractMethod<[], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "getMatch"
  ): TypedContractMethod<
    [matchId: BigNumberish],
    [RockPaperArena.MatchStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPendingMatches"
  ): TypedContractMethod<[], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getPlayerStats"
  ): TypedContractMethod<
    [player: AddressLike],
    [RockPaperArena.PlayerStatsStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "lockMove"
  ): TypedContractMethod<[matchId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "matchCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "matches"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        string,
        boolean,
        boolean,
        bigint,
        bigint,
        string
      ] & {
        matchId: bigint;
        player1: string;
        player2: string;
        move1: string;
        move2: string;
        player1Committed: boolean;
        player2Committed: boolean;
        createdAt: bigint;
        state: bigint;
        winner: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "pendingMatches"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "playerActiveMatch"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "playerStats"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        wins: bigint;
        losses: bigint;
        draws: bigint;
        totalMatches: bigint;
        currentStreak: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "requestReveal"
  ): TypedContractMethod<[matchId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitMove"
  ): TypedContractMethod<
    [matchId: BigNumberish, encryptedMove: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateStreak"
  ): TypedContractMethod<[arg0: AddressLike, arg1: boolean], [void], "view">;

  getEvent(
    key: "MatchCancelled"
  ): TypedContractEvent<
    MatchCancelledEvent.InputTuple,
    MatchCancelledEvent.OutputTuple,
    MatchCancelledEvent.OutputObject
  >;
  getEvent(
    key: "MatchCreated"
  ): TypedContractEvent<
    MatchCreatedEvent.InputTuple,
    MatchCreatedEvent.OutputTuple,
    MatchCreatedEvent.OutputObject
  >;
  getEvent(
    key: "MatchJoined"
  ): TypedContractEvent<
    MatchJoinedEvent.InputTuple,
    MatchJoinedEvent.OutputTuple,
    MatchJoinedEvent.OutputObject
  >;
  getEvent(
    key: "MatchRevealed"
  ): TypedContractEvent<
    MatchRevealedEvent.InputTuple,
    MatchRevealedEvent.OutputTuple,
    MatchRevealedEvent.OutputObject
  >;
  getEvent(
    key: "MoveCommitted"
  ): TypedContractEvent<
    MoveCommittedEvent.InputTuple,
    MoveCommittedEvent.OutputTuple,
    MoveCommittedEvent.OutputObject
  >;

  filters: {
    "MatchCancelled(uint256)": TypedContractEvent<
      MatchCancelledEvent.InputTuple,
      MatchCancelledEvent.OutputTuple,
      MatchCancelledEvent.OutputObject
    >;
    MatchCancelled: TypedContractEvent<
      MatchCancelledEvent.InputTuple,
      MatchCancelledEvent.OutputTuple,
      MatchCancelledEvent.OutputObject
    >;

    "MatchCreated(uint256,address)": TypedContractEvent<
      MatchCreatedEvent.InputTuple,
      MatchCreatedEvent.OutputTuple,
      MatchCreatedEvent.OutputObject
    >;
    MatchCreated: TypedContractEvent<
      MatchCreatedEvent.InputTuple,
      MatchCreatedEvent.OutputTuple,
      MatchCreatedEvent.OutputObject
    >;

    "MatchJoined(uint256,address)": TypedContractEvent<
      MatchJoinedEvent.InputTuple,
      MatchJoinedEvent.OutputTuple,
      MatchJoinedEvent.OutputObject
    >;
    MatchJoined: TypedContractEvent<
      MatchJoinedEvent.InputTuple,
      MatchJoinedEvent.OutputTuple,
      MatchJoinedEvent.OutputObject
    >;

    "MatchRevealed(uint256,address,uint8)": TypedContractEvent<
      MatchRevealedEvent.InputTuple,
      MatchRevealedEvent.OutputTuple,
      MatchRevealedEvent.OutputObject
    >;
    MatchRevealed: TypedContractEvent<
      MatchRevealedEvent.InputTuple,
      MatchRevealedEvent.OutputTuple,
      MatchRevealedEvent.OutputObject
    >;

    "MoveCommitted(uint256,address)": TypedContractEvent<
      MoveCommittedEvent.InputTuple,
      MoveCommittedEvent.OutputTuple,
      MoveCommittedEvent.OutputObject
    >;
    MoveCommitted: TypedContractEvent<
      MoveCommittedEvent.InputTuple,
      MoveCommittedEvent.OutputTuple,
      MoveCommittedEvent.OutputObject
    >;
  };
}
